### ISSUE TITLE
Scaling does not work after windows update.

### ISSUE THREAD

**Issue by Jaurocha** [mgth/LittleBigMouse#88] opened 2019-03-19 15:16 UTC
After a current windows update the scale do not apply anymore.
I have screens that are of different width in pixels and therefore I need to stretch one of the screens to make the pointer appear at the corresponding corners. 
This worked perfectly until the latest windows update I installed. After that the scaling is not applied any more and the pointer appear in the middle of one edge when leaving the corner of another instead of in the corresponding corner.

Any suggestions on how to fix this?

**Comment by gbaman** [comment] 2019-03-21 09:27
I believe this issue is a duplicate of https://github.com/mgth/LittleBigMouse/issues/84

**Comment by Jaurocha** [comment] 2019-03-21 10:29
No I do not believe it is. lbm starts and works fine except for the scaling.
The tray icon is there and Horizontal loop is in effect.
The only thing that do not work is the stretch/scaling of the displays.
So moving from a big display to a small one works as expected but not when moving from a small to a big one.

My monitors are of very different size I attach an image of my setup with the problem areas marked in red.
![lbm](https://user-images.githubusercontent.com/48325677/54746402-60be3300-4bcc-11e9-9024-552421bafcf1.jpg)

**Comment by mgth** [comment] 2019-07-01 22:14
New 4.3 version should fix that

**Closed by mgth** 2019-07-01 22:14 UTC
