### ISSUE TITLE
Mouse bug in game (Fortnite)

### ISSUE THREAD

**Issue by soggaaa** [mgth/LittleBigMouse#97] opened 2019-07-14 13:18 UTC
Hello,
I have a strange problem that happened when playing Fortnite. My left click button doesn't work properly. Sometimes when i click it doesn't shoot. It's maybe every 2 or 3 clicks it shoots, and sometimes it will get stuck shooting and just keep firing shots and reloading automatically until i click the button 2 or 3 times again.

Took me time to figure it out, but disabling LBM or going back to 4.1.6598.15330 solve the problem. Pretty sure, my update done this morning is in cause

**Comment by soggaaa** [comment] 2019-07-14 13:19
Disable LBM or going back to 4.1.6598.15330 solve the problem

**Comment by bogelboogaloo** [comment] 2019-09-22 23:36
i have this problem in pubg and fortnite with both mouse buttons. so aiming and shooting don't register sometimes. I tracked the problem to when I move my mouse hard to the left, which is where my secondary monitor is. was using 4.2.7124.42685 and I'm glad you found a fix. I'm going that older version rn

**Comment by bogelboogaloo** [comment] 2019-09-22 23:41
rolling back to 4.1.6598.15330 fixed my problem, idk why exactly this occurs, but I'm happy theres a version of LBM that doesnt have this issue

**Comment by EricM81** [comment] 2019-10-05 16:13
I just figured out that little big mouse was causing this problem.  I've been tearing my hair out and finally started trapping mouse events.  Win10 is registering each event, but the game was missing occasional LMB down, LMB  up, or entire LMB dwn/up combos.  

It's stopping the game from fully capturing the mouse, and it's easy to replicate the behavior.  When the mouse appears locked to the game monitor, drag it towards the other monitor and press mouse buttons.  Eventually, the game will cease to receive button click events.

**Comment by gitCommitWiL** [comment] 2019-11-08 11:55
This issue has been plaguing me for months and I had no idea what the cause was! First I thought there was an issue with my mouse so I got a new one (tbh, I wanted to upgrade anyways). Then I thought maybe my keypad was messing it up somehow? Then I thought maybe it was a bug in Fortnite? But I couldn't find any topics on the issue. Finally I had enough and decided to spend as much time as needed to narrow down the issue. After like an hour of trying every key + mouse combination, I finally discovered left click + swinging left or right quickly causes the issue. Closed every background program and tested one by one until LBM was closed.

I'm glad there's an "solution" of some sort; it was driving me insane!

**Comment by MJcato** [comment] 2020-04-23 17:04
little big mouse was causing the issue for me too, thanks guys, guess i'll try out display fusion them

**Comment by Spiritreader** [comment] 2020-04-29 08:23
Afaik with the newest version of LBM it happens with all Unreal Engine Games

**Comment by Zerglass** [comment] 2020-05-29 18:14
It has happened to me in Overwatch and Minecraft as well.

**Comment by swiftaes** [comment] 2020-06-18 00:27
Also had this issue was so annoying until I was able to find this, thanks for headsup. I'll just close it while gaming until its fixed.

**Comment by nilslorand** [comment] 2020-06-23 10:26
Rolling back to 4.1.6598.15330 didn't work for me because then the application simply refuses to start

**Comment by FREDYJ300** [comment] 2020-10-12 20:03
what is the solution?

**Comment by swiftaes** [comment] 2020-10-13 01:08
> 
> 
> what is the solution?

only way it stopped is when i disabed the program until im done playing quite unfortunate

**Comment by Down200** [comment] 2020-11-25 05:55
When you right-click the program and click "stop" it should fix the issue, just remember to re-enable it afterward.

**Comment by VinceBT** [comment] 2022-01-31 16:00
Please try this and add your game to the settings https://github.com/VinceBT/LBMM

**Closed** 2023-12-12 00:23 UTC
