### ISSUE TITLE
Incorrect cursor alignment

### ISSUE THREAD

**Issue by SunnyMoo** [mgth/LittleBigMouse#93] opened 2019-04-28 16:39 UTC
Hi, I've two different size monitors, big on bottom little on top.
Without LBM there's an inch of decal that prevent cursor moving between monitors.
With LBM decal is fixed only when I move cursor from big monitor to little monitor. It remains the same misalignment when moving cursor from top monitor to bottom monitor.
Ugly explanation pic attached.
![ugliestpicever](https://user-images.githubusercontent.com/50081326/56867392-1ce0f980-69d4-11e9-8691-e427043dbbb1.png)

Thanks !

**Comment by AcmeZexe** [comment] 2019-06-10 23:07
Possible duplicate of #88

**Comment by mgth** [comment] 2019-07-03 22:04
that should work now

**Closed by mgth** 2019-07-03 22:04 UTC

**Comment by SunnyMoo** [comment] 2019-07-04 16:24
It works, thank you !
