### ISSUE TITLE
When in windowed fullscreen game, mouse movements can appear on another screen

### ISSUE THREAD

**Issue by ASmyrnyi** [mgth/LittleBigMouse#321] opened 2024-03-11 18:04 UTC
I experience such a problem where cursor can appear for a moment on the monitor which doesn't have a game on it when moving the mouse towards the screen edge. When it happens, any click while cursor is not on a monitor with game on it leads to alt-tabing out of the game. Such behavior does not occur when LittleBigMouse is disabled.

**Comment by FoatGernando** [comment] 2024-03-12 00:03
Currently seeing this same issues too on newest release 5.1.0.0

Did a little regression testing and see it on previous versions such as 5.0.4.1 and 5.0.2.0

**Comment by FoatGernando** [comment] 2024-03-12 00:36
Update above, downloaded version: 4.2.7120.40854 and I am not seeing this problem anymore, will stick with this version until fix is implemented with version 5

**Comment by ASmyrnyi** [comment] 2024-03-12 15:38
I tried to do as mentioned [here](https://github.com/mgth/LittleBigMouse/issues/302) (adding process name to Excluded.txt) but it didn't work

**Comment by mgth** [comment] 2024-03-12 15:49
> I tried to do as mentioned [here](https://github.com/mgth/LittleBigMouse/issues/302) (adding process name to Excluded.txt) but it didn't work

It's the right way to deal with it.
Which game is it ? 
You have to add a line with a part of the game executable path.

**Comment by ASmyrnyi** [comment] 2024-03-12 17:28
> Which game is it ?

Game called 'Mordhau', I added this lines into Excluded.txt
\Mordhau\
\Mordhau-Win64-Shipping\
Also, since I play it via steam, shouldn't just the '\steamapps\' in txt file work?

**Comment by knguyen298** [comment] 2024-03-14 13:30
I am also experiencing this issue, mainly in Destiny 2. I was on 5.0.5.0 since January 11th on a fresh install of Windows, without any issue. I updated to 5.1.0.0, and noticed that I would lose focus of the game, primarily during quick, large mouse movements. Also noticed my cursor in game would line up to my cursor in Windows when I moved my cursor to my second monitor, as if LBM was still working. On 5.0.5.0, the cursor jumps as it would if LBM was turned off.

I have `\destiny2\` listed in the excluded file in an attempt to resolve the regression with 5.1.0.0., but the issue is still there.

**Comment by ViniRust** [comment] 2024-03-24 04:38
After updating to the newer 5.1.0.0 version, I'm also see this behavior. Stopping the program (not closing) is enough to solve it, but wasn't needed in previous versions.

**Comment by ViniRust** [comment] 2024-03-24 04:53
![image](https://github.com/mgth/LittleBigMouse/assets/13807964/734a1491-5126-4a59-882d-84c2edf60098)

**Closed** 2024-04-27 11:00 UTC

**Comment by fddn** [comment] 2024-12-03 20:26
@mgth this is still an issue in version 5.2.3.0.

**Comment by Bsiate** [comment] 2025-02-10 16:27
@mgth can confirm, still an issue in v5.2.3.0, specifically Valorant.

**Comment by PrinceEGY** [comment] 2025-02-26 03:03
@mgth yup, this still exists and I have to close the tool every time I want to game, appears on almost every game

**Comment by unsureboolean** [comment] 2025-04-04 18:28
@mgth Confirmed this is still an issue on 5.2.3.0

**Comment by Sen1604** [comment] 2025-05-24 22:12
Also having this issue, happens on every game ive tried so far

**Comment by tillsmc** [comment] 2026-03-06 20:14
Also having this issue. Also couldn't find an Excluded.txt.. anyone has a workaround? (The python script in the other thread does not seem to work for me either)

**Comment by Bsiate** [comment] 2026-03-28 16:42
Also having the issue; opening littlebigmouse from the small icon in the taskbar causes two instances of littlebigmouse to open.
After closing both with "X" it hides in the task bar again, fixes the issue and only opens one instasce of littlebigmouse when opening again.
